### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by chameleon-tbn** [goldilocks25/LiveStreamRadioMod#1] opened 2024-04-05 14:52 UTC
Hello, do this mod need Extended Radio as a dependency or do it work without? If it need this mod as dependency, it would be good adding this in PDXMods.

I write here, as you have comments deactivated on PDXMods

**Comment by goldilocks25** [comment] 2024-04-06 08:07
This mode does not require Extended radio.
Initially, there were dependencies, but now they have been removed due to significant differences in playback methods.

**Comment by chameleon-tbn** [comment] 2024-04-06 20:47
But they Not conflict with each other either, or?

**Comment by goldilocks25** [comment] 2024-04-07 03:32
Compatibility issues with Extended Radio have been confirmed to be non-existent. We would appreciate it if you could provide detailed information about the issue. Thank you.

**Comment by chameleon-tbn** [comment] 2024-04-07 07:20
Good to know, that there are No conflicts. I'll maintain this information in Skyve's Compatibility Data.

**Comment by goldilocks25** [comment] 2024-04-07 09:09
Thank you. I'll close the issue.

**Closed as completed** 2024-04-07 09:10 UTC
